services:
  redis:
    image: redis/redis-stack:7.2.0-v14
    expose:
      - 6379
      - 8001
    ports:
      - '6379:6379'
    command: [ "/entrypoint.sh", "./redis-stack.conf" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - /redis_data:/data
    environment:
      REDIS_ARGS: "--requirepass ${REDIS_PASSWORD}"